In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

from matplotlib import font_manager, rc
f_path = "c:/Windows/Fonts/malgun.ttf"
font_name = font_manager.FontProperties(fname=f_path).get_name()
rc('font', family=font_name)

### Load Data

In [33]:
df = pd.read_csv('./bunkae_data.csv')
df # 최신순

,Unnamed: 0,ad,bizseller,checkout,contact_hope,free_shipping,is_adult,is_super_up_shop,location,max_cpc,...,style,super_up,tag,uid,update_time,used,bun_pay_filter_enabled,imp_id,ad_ref,faved
0,0,False,False,False,False,False,False,NaN,서울특별시 중구 동화동,NaN,...,NaN,NaN,나이키 덩크로우 범고래 240 새상품,3584822,1636518640,2,True,3903618b4b6d08dc7c70,NaN,False
1,1,False,False,False,False,False,False,NaN,서울특별시 강남구 대치2동,NaN,...,NaN,NaN,나이키범고래 270 나이키덩크로우 나이키덩크로우범고 범고래,6524709,1636518563,1,False,3903618b4b6d08dc7c71,NaN,False
2,2,False,False,False,False,True,False,NaN,NaN,NaN,...,NaN,NaN,나이키덩크로우,12322749,1636518444,1,False,3903618b4b6d08dc7c72,NaN,False
3,3,False,False,False,False,True,False,NaN,인천광역시 남구 용현2동,NaN,...,NaN,NaN,나이키 범고래 덩크로우,1583666,1636518316,2,False,3903618b4b6d08dc7c73,NaN,False
4,4,False,False,False,False,False,False,NaN,NaN,NaN,...,NaN,NaN,나이키 덩크 범고래 나이키덩크로우 230,74796866,1636518197,2,True,3903618b4b6d08dc7c74,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912,1912,False,False,False,False,True,False,NaN,서울특별시 노원구 중계2.3동,NaN,...,NaN,NaN,덩크로우 범고래 범고래275 나코택,7760227,1618558233,2,False,380c618b4b7c00b4f781,NaN,False
1913,1913,False,False,False,False,False,False,NaN,NaN,NaN,...,NaN,NaN,범고래 나이키 범고래235 덩크 덩크로우,6063511,1618139744,13,False,380c618b4b7c00b4f782,NaN,False
1914,1914,False,False,False,False,False,False,NaN,대구광역시 동구 안심2동,NaN,...,NaN,NaN,265 범고래 나이키 덩크로우,2008437,1617331125,2,False,380c618b4b7c00b4f783,NaN,False
1915,1915,False,False,False,True,True,False,NaN,인천광역시 부평구 산곡2동,NaN,...,NaN,NaN,나이키 덩크로우 범고래 260 검은색,415346,1611390073,13,False,380c618b4b7c00b4f784,NaN,False
1916,1916,False,False,False,False,True,False,NaN,서울특별시 노원구 중계2.3동,NaN,...,NaN,NaN,나이키 덩크로우 범고래 275 나코택,7760227,1610288818,2,False,380c618b4b7c00b4f785,NaN,False