In [1]:
!pip3 install selenium

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests 
from bs4 import BeautifulSoup

Requirement already satisfied: selenium in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (4.0.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from selenium) (1.26.4)
Requirement already satisfied: attrs>=19.2.0 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: idna in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: sniffio in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (1.14.5)
Requirement already satisfied: outcome in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sortedcontainers in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: pycparser in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from urllib3[secure]~=1.26->selenium) (20.0.1)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from urllib3[secure]~=1.26->selenium) (3.4.7)
Requirement already satisfied: certifi in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2020.12.5)
Requirement already satisfied: six>=1.5.2 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\82105\anaconda3\envs\fc_bda\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)

In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [13]:
import json

In [109]:
## 번개장터 코드
import pandas as pd
import numpy as np
import json
import time
import requests

bunjang_df = pd.DataFrame()

info = {
    'referer' : 'https://m.bunjang.co.kr/',
    'user-agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36' 
    }

for i in range(0, 10):
    
    seed = np.random.randint(100)
    np.random.seed(seed)
    a = np.random.randint(5)
    time.sleep(a)
    
    url = f'https://api.bunjang.co.kr/api/1/find_v2.json?q=%EB%82%98%EC%9D%B4%ED%82%A4+%EB%8D%A9%ED%81%AC%EB%A1%9C%EC%9A%B0+%EB%B2%94%EA%B3%A0%EB%9E%98&order=date&page={i}&request_id=20211110132819&stat_device=w&n=100&stat_category_required=1&req_ref=search&version=4'
    
    print(f'{i}페이지 크롤링중...')
    
    resp = requests.get(url, headers=info)
    
    if resp.status_code == requests.codes.ok:
        data = json.loads(resp.text)
        df = pd.DataFrame(data['list'])
        bunjang_df = pd.concat([df, bunjang_df])
    
    else:
        print(f'{page}페이지 요청이 잘못되었습니다.')
        pass

print("크롤링 완료.")

0페이지 크롤링중...
1페이지 크롤링중...
2페이지 크롤링중...
3페이지 크롤링중...
4페이지 크롤링중...
5페이지 크롤링중...
6페이지 크롤링중...
7페이지 크롤링중...
8페이지 크롤링중...
9페이지 크롤링중...
크롤링 완료.

In [110]:
bunjang_df['pid'].value_counts()

165576452    2
169330753    2
169426341    2
150038541    1
166482790    1
            ..
168643559    1
143704450    1
166835958    1
169177532    1
169198399    1
Name: pid, Length: 997, dtype: int64

In [98]:
bunjang_df

,ad,bizseller,checkout,contact_hope,free_shipping,is_adult,is_super_up_shop,location,max_cpc,name,...,style,super_up,tag,uid,update_time,used,bun_pay_filter_enabled,imp_id,ad_ref,faved
0,False,False,False,False,False,False,None,서울특별시 동작구 노량진제1동,None,나이키 덩크로우 범고래 235,...,,None,범고래 나이키 덩크로우 235,12556128,1636508918,1,False,3350618b267a0033c1cc,,False
1,False,False,False,False,False,False,None,부산광역시 부산진구 당감제2동,None,나이키 우먼스 덩크로우 범고래 w240,...,,None,나이키덩크로우범고래 범고래240,5532643,1636508374,1,False,3350618b267a0033c1cd,,False
2,False,False,False,False,False,False,None,경기도 고양시 일산서구 일산3동,None,나이키 덩크로우 범고래 270,...,,None,나이키 덩크로우 나이키덩크로우범고래 270,77700435,1636508232,1,True,3350618b267a0033c1ce,,False
3,False,False,False,False,False,False,None,경기도 성남시 분당구 야탑1동,None,[235]나이키 덩크로우 범고래,...,,None,나이키덩크로우범고 나이키 덩크 나이키덩크 나이키덩크235,765261,1636507920,1,False,3350618b267a0033c1cf,,False
4,False,False,False,False,True,False,None,경기도 안양시 만안구 안양7동,None,나이키 덩크로우 범고래 우먼스 w250mm 새제품,...,,None,나이키 나이키덩크로우범고,77173379,1636508077,1,False,3350618b267a0033c1d0,,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,None,경기도 고양시 일산동구 정발산동,None,나이키 덩크로우 범고래 우먼스 240,...,,None,,9442801,1636457995,1,False,24ab618b266206b5afb3,,False
96,False,False,False,False,False,False,None,부산광역시 남구 용호제2동,None,범고래 260 나이키 덩크로우 레토르,...,,None,범고래,77829496,1636440351,2,False,24ab618b266206b5afb4,,False
97,False,False,False,False,False,False,None,전라북도 고창군 고창읍,None,우먼스나이키덩크로우범고래225,...,,None,나이키 덩크로우225 범고래 나이키덩크로우범고래 우먼스,10305650,1636433946,1,True,24ab618b266206b5afb5,,False
98,False,False,False,False,False,False,None,인천광역시 남동구 만수5동,None,나이키 덩크로우 범고래 우먼스 w235,...,,None,나이키 덩크 범고래 235,216001,1636463838,1,False,24ab618b266206b5afb6,,False
99,False,False,False,False,False,False,None,,None,(235)나이키 w덩크로우 범고래 우먼스,...,,None,나이키덩크 덩크로우범고래 나이키범고래 범고래덩크 나이키덩크로우범고래,11933543,1636460503,1,False,24ab618b266206b5afb7,,False

In [97]:
bunjang_df.columns
bunjang_df[bunjang_df['status'] == '1']

,ad,bizseller,checkout,contact_hope,free_shipping,is_adult,is_super_up_shop,location,max_cpc,name,...,style,super_up,tag,uid,update_time,used,bun_pay_filter_enabled,imp_id,ad_ref,faved
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,3350618b267a0033c1d5,,False
86,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,3350618b267a0033c222,,False
96,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,3350618b267a0033c22c,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,24ab618b267706b63e94,,False
87,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,24ab618b267706b63ee2,,False
93,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,24ab618b267706b63ee8,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,3350618b26770033aa29,,False
86,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,3350618b26770033aa76,,False
96,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,3350618b26770033aa80,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,3350618b2673003385a2,,False
89,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,3350618b2673003385f2,,False
93,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,3350618b2673003385f6,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,2993618b26700768200b,,False
86,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,2993618b267007682058,,False
94,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,2993618b267007682060,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,24ab618b266d06b5f9c3,,False
88,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,24ab618b266d06b5fa12,,False
93,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,24ab618b266d06b5fa17,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,2993618b266d076805c7,,False
88,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,2993618b266d07680616,,False
93,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,2993618b266d0768061b,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,2993618b26680767e518,,False
87,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,2993618b26680767e567,,False
94,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,2993618b26680767e56e,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,3903618b266507ce25ec,,False
88,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,3903618b266507ce263b,,False
93,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,3903618b266507ce2640,,False
9,False,False,False,False,False,False,None,부산광역시 영도구 동삼제3동,None,나이키 덩크로우 범고래 235mm,...,,None,나이키 덩크로우 나이키덩크로우범고래 나이키덩크로우범고래235 235,10425233,1636506462,1,False,24ab618b266206b5af5d,,False
89,False,False,False,False,True,False,None,서울특별시 종로구 평창동,None,나이키 덩크로우 범고래(265)새제품,...,,None,덩크로우 범고래,7266215,1636456281,1,False,24ab618b266206b5afad,,False
93,False,False,False,False,False,False,None,경상남도 창원시 의창구 봉림동,None,나이키 덩크로우 범고래 우먼스 245,...,,None,나이키 덩크로우 범고래 우먼스 245,76742906,1636451708,1,False,24ab618b266206b5afb1,,False

In [ ]:
# coulumn : num,날짜,size,착용횟수??, 중고여부, (색상), 
# coulumn : num, 

# 가격에 영향을 미치는 요소

In [ ]:
'''
name column 에서 숫자만 추출하여 
대략적인 size data 구함
'''

## string data 에서 숫자(사이즈) 추출하는 코드 ##

import re

size = []

# df index 범위만큼 for문 돌림 #
for i in range(0, len(bunjang_df)):
    size.append(re.sub(r'[^0-9]','',bunjang_df['name'].values[i]))

size_df = pd.DataFrame(size)
size_df.columns = ['size']
size